# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfirmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBinaryFW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.IntegerField()),
                ('valn_function_name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('data_binary', models.TextField()),
            ],
        ),
    ]
