# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfigureFW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.IntegerField()),
                ('configure_name', models.CharField(max_length=50)),
                ('data_configure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableHtmlFW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.IntegerField()),
                ('html_name', models.CharField(max_length=50)),
                ('data_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableNameFW',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('name_firmawre_1', models.CharField(max_length=50)),
                ('name_firmawre_2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TableOtherFW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.IntegerField()),
                ('other_name', models.CharField(max_length=50)),
                ('data_other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableScriptsFW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.IntegerField()),
                ('script_name', models.CharField(max_length=50)),
                ('data_script', models.TextField()),
            ],
        ),
    ]
